# https://alacritty.org/config-alacritty.html

[window]
padding = { x = 8, y = 8 }
# opacity = 0.75

[font]
size = 12.0

[font.normal]
family = "Roboto Mono"

[general]
import = [
    "~/.config/alacritty/themes/matugen-theme.toml"
]
